name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name : login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }} 
        run: heroku login
      - name: push
      env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}