name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name : heroku push
    env:
       HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}} 
    run: git push heroku main