name: Deploy


on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Heroku Pull
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: git pull heroku main
    - name: Heroku Push
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: git push heroku main